/* Copyright 2018, Socializing Syndicate Corp. */
const APP_TITLE = `Let's Go`
const DATE_FORMAT = 'MM/DD/YYYY'
const TIME_FORMAT = 'HH:mm'

const VERIFICATION_STARTED = 'VERIFICATION_STARTED'
const LOGIN_START = 'LOGIN_START'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILED = 'LOGIN_FAILED'
const LOGOUT = 'LOGOUT'
const SIGNUP_START = 'SIGNUP_START'
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
const SIGNUP_FAILED = 'SIGNUP_FAILED'

const FETCH_EVENT_FEEDS_START = 'FETCH_EVENT_FEEDS_START'
const FETCH_EVENT_FEEDS = 'FETCH_EVENT_FEEDS'
const ADD_NEW_EVENT = 'ADD_NEW_EVENT'
const FETCH_MY_EVENTS = 'FETCH_MY_EVENTS'
const REQUEST_SUBMIT = 'REQUEST_SUBMIT'

const FETCH_USER = 'FETCH_USER'

const COUNT_DOWN_START = 'COUNT_DOWN_START'
const COUNTING_DOWN = 'COUNTING_DOWN'
const COUNT_DOWN_FINISH = 'COUNT_DOWN_FINISH'

const HOST_VIEW_REQUEST = 'HOST_VIEW_REQUEST'

const EDIT_USER_START = 'EDIT_USER_START'
const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
const EDIT_USER_FAILED = 'EDIT_USER_FAILED'
const EDIT_USER_CANCEL = 'EDIT_USER_CANCEL'

export {
  APP_TITLE,
  DATE_FORMAT,
  TIME_FORMAT,
  HOST_VIEW_REQUEST,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  SIGNUP_START,
  SIGNUP_SUCCESS,
  SIGNUP_FAILED,
  VERIFICATION_STARTED,
  FETCH_EVENT_FEEDS_START,
  FETCH_EVENT_FEEDS,
  ADD_NEW_EVENT,
  FETCH_MY_EVENTS,
  FETCH_USER,
  COUNT_DOWN_START,
  COUNTING_DOWN,
  COUNT_DOWN_FINISH,
  REQUEST_SUBMIT,
  EDIT_USER_START,
  EDIT_USER_SUCCESS,
  EDIT_USER_FAILED,
  EDIT_USER_CANCEL
}
